do local _ = {
  about_text = "https://telegram.me/VIP_TEAM1",
  enabled_plugins = {
    "plugins",
    "admin",
    "all",
    "anti_spam",
    "arabic_lock",
    "lock_all",
    "banhammer",
    "broadcast",
    "dowelcome",
    "echo",
    "dobye",
    "FWD",
    "filter",
    "get",
    "helpall",
    "image23",
    "helps.pv",
    "infoeng",
    "ingroup",
    "inpm",
    "inrealm",
    "invite",
    "instagram",
    "l1",
    "l2",
    "l3",
    "l4",
    "l5",
    "linkpv",
    "leave_ban",
    "lock_badword",
    "lock_emoji",
    "lock_english",
    "lock_fwd",
    "lock_join",
    "lock_media",
    "lock_reply",
    "lock_tag",
    "lock_username",
    "m",
    "me",
    "music_eng",
    "n",
    "onservice",
    "msg_checks",
    "owners",
    "password",
    "rebot",
    "redis",
    "set",
    "set_type",
    "short_link",
    "silent",
    "stats",
    "sticker23",
    "tag_english",
    "textphoto",
    "supergroup",
    "sudo",
    "time",
    "translate",
    "voice",
    "weather",
    "whitelist",
    "zahrfarav",
    "raeplybot",
    "me_music",
    "runrun",
    "VIPBOT",
    "dletemsg",
    "block",
    "sendd",
    "welcome",
    "mu",
    "sendme",
    "aa",
    "ping",
    "activeuser",
    "run2",
    "rp",
    "pi"
  },
  help_text = "",
  help_text_realm = "",
  help_text_super = "",
  moderation = {
    data = "data/moderation.json"
  },
  sudo_users = {
    231068109,
    125123752,
    79670942,
    237850698,
    218827876
  }
}
return _
end